// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data-service.proto

package ppdata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InstMsgRequest struct {
	StartTime            int32    `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	DeviceEUI            string   `protobuf:"bytes,2,opt,name=deviceEUI,proto3" json:"deviceEUI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstMsgRequest) Reset()         { *m = InstMsgRequest{} }
func (m *InstMsgRequest) String() string { return proto.CompactTextString(m) }
func (*InstMsgRequest) ProtoMessage()    {}
func (*InstMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60c109ad3fe637bb, []int{0}
}

func (m *InstMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstMsgRequest.Unmarshal(m, b)
}
func (m *InstMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstMsgRequest.Marshal(b, m, deterministic)
}
func (m *InstMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstMsgRequest.Merge(m, src)
}
func (m *InstMsgRequest) XXX_Size() int {
	return xxx_messageInfo_InstMsgRequest.Size(m)
}
func (m *InstMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstMsgRequest proto.InternalMessageInfo

func (m *InstMsgRequest) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *InstMsgRequest) GetDeviceEUI() string {
	if m != nil {
		return m.DeviceEUI
	}
	return ""
}

type InstMsgData struct {
	Rows                 []*InstMsgDatum `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InstMsgData) Reset()         { *m = InstMsgData{} }
func (m *InstMsgData) String() string { return proto.CompactTextString(m) }
func (*InstMsgData) ProtoMessage()    {}
func (*InstMsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_60c109ad3fe637bb, []int{1}
}

func (m *InstMsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstMsgData.Unmarshal(m, b)
}
func (m *InstMsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstMsgData.Marshal(b, m, deterministic)
}
func (m *InstMsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstMsgData.Merge(m, src)
}
func (m *InstMsgData) XXX_Size() int {
	return xxx_messageInfo_InstMsgData.Size(m)
}
func (m *InstMsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_InstMsgData.DiscardUnknown(m)
}

var xxx_messageInfo_InstMsgData proto.InternalMessageInfo

func (m *InstMsgData) GetRows() []*InstMsgDatum {
	if m != nil {
		return m.Rows
	}
	return nil
}

type InstMsgDatum struct {
	Timestamp            int32    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Phase                int32    `protobuf:"varint,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Voltage              float32  `protobuf:"fixed32,3,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current              float32  `protobuf:"fixed32,4,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstMsgDatum) Reset()         { *m = InstMsgDatum{} }
func (m *InstMsgDatum) String() string { return proto.CompactTextString(m) }
func (*InstMsgDatum) ProtoMessage()    {}
func (*InstMsgDatum) Descriptor() ([]byte, []int) {
	return fileDescriptor_60c109ad3fe637bb, []int{2}
}

func (m *InstMsgDatum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstMsgDatum.Unmarshal(m, b)
}
func (m *InstMsgDatum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstMsgDatum.Marshal(b, m, deterministic)
}
func (m *InstMsgDatum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstMsgDatum.Merge(m, src)
}
func (m *InstMsgDatum) XXX_Size() int {
	return xxx_messageInfo_InstMsgDatum.Size(m)
}
func (m *InstMsgDatum) XXX_DiscardUnknown() {
	xxx_messageInfo_InstMsgDatum.DiscardUnknown(m)
}

var xxx_messageInfo_InstMsgDatum proto.InternalMessageInfo

func (m *InstMsgDatum) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *InstMsgDatum) GetPhase() int32 {
	if m != nil {
		return m.Phase
	}
	return 0
}

func (m *InstMsgDatum) GetVoltage() float32 {
	if m != nil {
		return m.Voltage
	}
	return 0
}

func (m *InstMsgDatum) GetCurrent() float32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterType((*InstMsgRequest)(nil), "ppdata.InstMsgRequest")
	proto.RegisterType((*InstMsgData)(nil), "ppdata.InstMsgData")
	proto.RegisterType((*InstMsgDatum)(nil), "ppdata.InstMsgDatum")
}

func init() { proto.RegisterFile("data-service.proto", fileDescriptor_60c109ad3fe637bb) }

var fileDescriptor_60c109ad3fe637bb = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x5d, 0xa0, 0x18, 0x06, 0x43, 0xe2, 0x4a, 0xcc, 0xc6, 0x78, 0x68, 0x7a, 0xda, 0x8b,
	0x3d, 0xe0, 0xc1, 0xa3, 0x17, 0x8c, 0x21, 0xd1, 0xcb, 0x8a, 0x3f, 0x60, 0x84, 0x09, 0x36, 0xb1,
	0x74, 0xdd, 0x9d, 0xd6, 0xbf, 0x6f, 0xb6, 0x5b, 0x2c, 0x91, 0xe3, 0x7b, 0x6f, 0x32, 0xf3, 0xcd,
	0x03, 0xb9, 0x45, 0xc6, 0x3b, 0x4f, 0xae, 0x29, 0x36, 0x94, 0x5b, 0x57, 0x71, 0x25, 0xc7, 0xd6,
	0x06, 0x37, 0x7b, 0x81, 0xd9, 0x6a, 0xef, 0xf9, 0xd5, 0xef, 0x0c, 0x7d, 0xd7, 0xe4, 0x59, 0xde,
	0xc2, 0xc4, 0x33, 0x3a, 0x5e, 0x17, 0x25, 0x29, 0x91, 0x0a, 0x9d, 0x98, 0xde, 0x08, 0xe9, 0x96,
	0xc2, 0x9e, 0xa7, 0xf7, 0x95, 0x1a, 0xa4, 0x42, 0x4f, 0x4c, 0x6f, 0x64, 0x0f, 0x30, 0xed, 0xb6,
	0x2d, 0x91, 0x51, 0x6a, 0x18, 0xb9, 0xea, 0xc7, 0x2b, 0x91, 0x0e, 0xf5, 0x74, 0x31, 0xcf, 0xe3,
	0xcd, 0xbc, 0x1f, 0xa9, 0x4b, 0xd3, 0x4e, 0x64, 0x0d, 0x5c, 0x1c, 0xbb, 0xe1, 0x0c, 0x17, 0x25,
	0x79, 0xc6, 0xd2, 0x1e, 0x20, 0xfe, 0x0c, 0x39, 0x87, 0xc4, 0x7e, 0xa2, 0xa7, 0x16, 0x20, 0x31,
	0x51, 0x48, 0x05, 0xe7, 0x4d, 0xf5, 0xc5, 0xb8, 0x23, 0x35, 0x4c, 0x85, 0x1e, 0x98, 0x83, 0x0c,
	0xc9, 0xa6, 0x76, 0x8e, 0xf6, 0xac, 0x46, 0x31, 0xe9, 0xe4, 0x62, 0x0d, 0x97, 0xcb, 0x96, 0x3e,
	0xf0, 0xbe, 0xc5, 0x86, 0xe4, 0x23, 0xcc, 0x9e, 0x89, 0x8f, 0x1f, 0xb9, 0xfe, 0x87, 0xde, 0x75,
	0x75, 0x73, 0x75, 0xfa, 0x12, 0x66, 0x67, 0x1f, 0xe3, 0xb6, 0xe3, 0xfb, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc3, 0x74, 0xdf, 0x7c, 0x79, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceDataServiceClient is the client API for DeviceDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceDataServiceClient interface {
	GetInstMsgData(ctx context.Context, in *InstMsgRequest, opts ...grpc.CallOption) (*InstMsgData, error)
}

type deviceDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeviceDataServiceClient(cc *grpc.ClientConn) DeviceDataServiceClient {
	return &deviceDataServiceClient{cc}
}

func (c *deviceDataServiceClient) GetInstMsgData(ctx context.Context, in *InstMsgRequest, opts ...grpc.CallOption) (*InstMsgData, error) {
	out := new(InstMsgData)
	err := c.cc.Invoke(ctx, "/ppdata.DeviceDataService/GetInstMsgData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceDataServiceServer is the server API for DeviceDataService service.
type DeviceDataServiceServer interface {
	GetInstMsgData(context.Context, *InstMsgRequest) (*InstMsgData, error)
}

// UnimplementedDeviceDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceDataServiceServer struct {
}

func (*UnimplementedDeviceDataServiceServer) GetInstMsgData(ctx context.Context, req *InstMsgRequest) (*InstMsgData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstMsgData not implemented")
}

func RegisterDeviceDataServiceServer(s *grpc.Server, srv DeviceDataServiceServer) {
	s.RegisterService(&_DeviceDataService_serviceDesc, srv)
}

func _DeviceDataService_GetInstMsgData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceDataServiceServer).GetInstMsgData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppdata.DeviceDataService/GetInstMsgData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceDataServiceServer).GetInstMsgData(ctx, req.(*InstMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ppdata.DeviceDataService",
	HandlerType: (*DeviceDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstMsgData",
			Handler:    _DeviceDataService_GetInstMsgData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data-service.proto",
}
