# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_service_pb2 as data__service__pb2


class DeviceDataServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetInstMsgData = channel.unary_unary(
        '/ppdata.DeviceDataService/GetInstMsgData',
        request_serializer=data__service__pb2.DataMsgRequest.SerializeToString,
        response_deserializer=data__service__pb2.InstMsgData.FromString,
        )
    self.GetProcMsgData = channel.unary_unary(
        '/ppdata.DeviceDataService/GetProcMsgData',
        request_serializer=data__service__pb2.DataMsgRequest.SerializeToString,
        response_deserializer=data__service__pb2.ProcMsgData.FromString,
        )
    self.GetPQMsgData = channel.unary_unary(
        '/ppdata.DeviceDataService/GetPQMsgData',
        request_serializer=data__service__pb2.DataMsgRequest.SerializeToString,
        response_deserializer=data__service__pb2.PQMsgData.FromString,
        )
    self.GetGeoscanMsgData = channel.unary_unary(
        '/ppdata.DeviceDataService/GetGeoscanMsgData',
        request_serializer=data__service__pb2.DataMsgRequest.SerializeToString,
        response_deserializer=data__service__pb2.GeoscanMsgData.FromString,
        )


class DeviceDataServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetInstMsgData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProcMsgData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPQMsgData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGeoscanMsgData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeviceDataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetInstMsgData': grpc.unary_unary_rpc_method_handler(
          servicer.GetInstMsgData,
          request_deserializer=data__service__pb2.DataMsgRequest.FromString,
          response_serializer=data__service__pb2.InstMsgData.SerializeToString,
      ),
      'GetProcMsgData': grpc.unary_unary_rpc_method_handler(
          servicer.GetProcMsgData,
          request_deserializer=data__service__pb2.DataMsgRequest.FromString,
          response_serializer=data__service__pb2.ProcMsgData.SerializeToString,
      ),
      'GetPQMsgData': grpc.unary_unary_rpc_method_handler(
          servicer.GetPQMsgData,
          request_deserializer=data__service__pb2.DataMsgRequest.FromString,
          response_serializer=data__service__pb2.PQMsgData.SerializeToString,
      ),
      'GetGeoscanMsgData': grpc.unary_unary_rpc_method_handler(
          servicer.GetGeoscanMsgData,
          request_deserializer=data__service__pb2.DataMsgRequest.FromString,
          response_serializer=data__service__pb2.GeoscanMsgData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ppdata.DeviceDataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
